// Hooper's Path - Drill Library
// Each drill is tagged with environments it works in:
//   fullct - full court available
//   halfct - half court (at least one hoop + half the lines)
//   hoop   - just a basketball hoop, no lines
//   nohoop - open space, ball ok, no hoop (driveway, gym floor)
//   noball - anywhere, no ball needed
//   homegym - weights, maybe pullup bar (garage/basement setup)
//   gym     - commercial gym with machines and racks
//
// New fields (Apr 2026):
//   prescription - specific instructions ("3 feet from rim, 50 shots for 50 makes")
//   cue          - one-line form tip read by voice coach during drill
//   youtube      - search query for video link-out

const ENVIRONMENTS = [
  { id: 'fullct', label: 'Full Court', icon: '🏟️', description: 'School gym, rec center' },
  { id: 'halfct', label: 'Half Court', icon: '🏀', description: 'Driveway, park, outdoor' },
  { id: 'hoop',   label: 'Hoop Only',  icon: '🥅', description: 'Just a rim, no lines' },
  { id: 'nohoop', label: 'No Hoop',    icon: '🔶', description: 'Open space, can bring ball' },
  { id: 'homegym',label: 'Home Gym',   icon: '🏠', description: 'Weights, pullup bar' },
  { id: 'gym',    label: 'Gym',        icon: '💪', description: 'Full commercial gym' },
];

const BASKETBALL_DRILLS = [
  // ============================================================
  // BALL HANDLING
  // ============================================================
  { id: "bh1", category: "ball-handling", name: "Pound Dribble",
    description: "Hard pound dribble, ball below knee. Stay low, keep eyes up.",
    prescription: "Get in athletic stance. Pound the ball as hard as you can below your knee. 30 seconds right hand, 30 seconds left, 30 seconds alternating. Repeat 2 rounds. Eyes up the entire time — pick a spot on the wall and stare at it.",
    cue: "Pound it harder. Eyes up.",
    youtube: "pound dribble drill basketball",
    baseReps: "2 sets x 30 sec each hand", difficulty: 1,
    why: "Builds hand strength and control for tight-space dribbling.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "bh2", category: "ball-handling", name: "Crossover Dribble",
    description: "Low crossovers side to side. Keep ball below waist.",
    prescription: "Stay low in a stance. Cross the ball hand to hand, keeping it below your waist. Push off the outside foot each crossover. 3 sets of 20 crossovers, no rest between sides. Rest 30 seconds between sets.",
    cue: "Stay low. Push off your outside foot.",
    youtube: "crossover dribble drill basketball form",
    baseReps: "3 sets x 20 crosses", difficulty: 1,
    why: "Foundation for breaking down defenders off the dribble.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "bh3", category: "ball-handling", name: "Figure 8 Dribble",
    description: "Dribble between legs in figure 8 pattern, stay low.",
    prescription: "Feet shoulder-width apart. Bounce the ball through your legs in a figure-8 pattern — front to back, around your right leg, then back to front through, around your left. 30 seconds going one direction, 30 reverse direction. Repeat 3 times.",
    cue: "Stay low. Wide base.",
    youtube: "figure 8 dribbling drill basketball",
    baseReps: "3 sets x 30 sec", difficulty: 2,
    why: "Coordinates both hands and improves spatial control.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "bh4", category: "ball-handling", name: "Two Ball Pound",
    description: "Two basketballs, pound dribble both at once.",
    prescription: "Grab two basketballs. Pound dribble both at the same time below your knees for 30 seconds. Then alternate (right hand down while left hand up) for 30 seconds. Then high-low (one ball waist-high, one knee-high) for 30 seconds. 2 full rounds.",
    cue: "Both hands work equally. Eyes up.",
    youtube: "two ball dribbling drill basketball",
    baseReps: "2 sets x 30 sec each variation", difficulty: 3,
    why: "Develops weak hand to match strong hand.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "bh5", category: "ball-handling", name: "Stationary Combo",
    description: "Crossover, between legs, behind back combos.",
    prescription: "Stay low in a stance. Cycle through these four moves with no pause: crossover, between the legs, behind the back, in-and-out. 10 reps of each move, then start over. Complete 4 full rounds.",
    cue: "No wasted motion. Quick hands.",
    youtube: "stationary basketball dribbling combo drill",
    baseReps: "4 sets x 10 reps each move", difficulty: 2,
    why: "Combines moves under fatigue, real game-like sequencing.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "bh6", category: "ball-handling", name: "Tennis Ball Toss",
    description: "Dribble while tossing tennis ball with off-hand.",
    prescription: "Hold a tennis ball in your off hand. Dribble a basketball with your strong hand while tossing the tennis ball straight up about head-high and catching it. Don't let the basketball bounce out of control. 30 seconds each hand. 3 rounds.",
    cue: "Don't watch the basketball. Watch the tennis ball.",
    youtube: "tennis ball dribbling drill basketball",
    baseReps: "3 sets x 30 sec each hand", difficulty: 3,
    why: "Forces eyes-up dribbling, improves court vision.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "bh7", category: "ball-handling", name: "Speed Dribble Length",
    description: "Full court speed dribble, push the pace.",
    prescription: "Start at the baseline. Dribble full court as fast as you can while staying in control. Right hand only down, left hand only back. 6 trips. Time yourself — try to beat your previous time without losing the ball.",
    cue: "Push the ball in front of you. Don't pat it.",
    youtube: "speed dribble drill full court basketball",
    baseReps: "6 trips full court", difficulty: 2,
    why: "Game-speed handle, transition offense ability.",
    envs: ["fullct"] },

  { id: "bh8", category: "ball-handling", name: "Cone Weave",
    description: "Set 5 cones, weave through using crossovers.",
    prescription: "Set 5 cones in a line, 3 feet apart. Start at the first cone. Crossover at each cone, alternating hands as you weave through. Touch the last cone, turn, weave back. 4 trips down and back. Speed it up each trip.",
    cue: "Tight crossovers. Don't go wide.",
    youtube: "cone weave dribble drill basketball",
    baseReps: "4 trips through 5 cones", difficulty: 2,
    why: "Change of direction with the ball, mimics defenders.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "bh9", category: "ball-handling", name: "Wall Dribble Series",
    description: "Various controlled dribble moves against the wall, no errors.",
    prescription: "Stand 3 feet from a wall. Dribble normally for 20 seconds — ball should not touch the wall. Then between-the-legs without ball touching wall, 20 seconds. Then behind-the-back, 20 seconds. 3 full rounds.",
    cue: "Control over speed.",
    youtube: "wall dribbling drill basketball",
    baseReps: "3 sets x 60 sec total", difficulty: 1,
    why: "Forces control under constraint, no room for error.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  // ============================================================
  // SHOOTING
  // ============================================================
  { id: "sh1", category: "shooting", name: "Form Shooting",
    description: "Close range one-handed form shots.",
    prescription: "Start 3 feet from the rim. One hand only — shooting hand under the ball, off hand at your side. Take 50 shots, going for 45+ makes. Reset and refocus on form if you miss two in a row.",
    cue: "Hand under the ball. Follow through.",
    youtube: "form shooting drill basketball one hand",
    baseReps: "50 shots, aim for 45 makes", difficulty: 1,
    why: "Locks in proper shooting mechanics. Most important shooting drill in basketball.",
    envs: ["fullct","halfct","hoop"] },

  { id: "sh2", category: "shooting", name: "Mikan Drill",
    description: "Right hand layup, rebound, left hand layup, repeat fast.",
    prescription: "Start under the rim. Shoot a right-hand layup off the backboard, catch it before it hits the ground, immediately shoot a left-hand layup. Keep going as fast as possible. Make 25 layups in a row (right, left, right, left). If you miss, restart count.",
    cue: "Quick feet. Don't catch and gather.",
    youtube: "mikan drill basketball",
    baseReps: "25 makes consecutive", difficulty: 1,
    why: "Both-hand finishing under the rim, conditioning, footwork.",
    envs: ["fullct","halfct","hoop"] },

  { id: "sh3", category: "shooting", name: "Spot Shooting (5 spots)",
    description: "Shoot from 5 spots: corners, wings, top of key.",
    prescription: "Set up at 5 spots: both corners, both wings, top of the key. Shoot 10 shots from each spot. 50 total shots, aim for 30+ makes. If you make 8 in a row from a spot, move to the next.",
    cue: "Square your shoulders to the rim. Same form every time.",
    youtube: "5 spot shooting drill basketball",
    baseReps: "50 shots, aim for 30 makes", difficulty: 2,
    why: "Builds shooting touch from common game spots.",
    envs: ["halfct","hoop"] },

  { id: "sh4", category: "shooting", name: "Catch and Shoot",
    description: "Self-pass, catch, shoot in rhythm.",
    prescription: "Start at the elbow. Toss the ball out toward the wing with backspin. Sprint to the wing, catch, square up, shoot in one motion. Get the rebound, walk back, repeat. 25 makes. Switch sides for another 25 makes.",
    cue: "Hands ready before the ball gets to you.",
    youtube: "catch and shoot drill basketball self pass",
    baseReps: "50 makes total (25 each side)", difficulty: 2,
    why: "Game-realistic shot off a pass.",
    envs: ["halfct","hoop"] },

  { id: "sh5", category: "shooting", name: "Free Throws (Pressure)",
    description: "Shoot free throws, track makes.",
    prescription: "Stand at the free throw line. Take 25 free throws. Track makes — try to beat your previous best. Same routine every time: bounce ball 3 times, breathe, shoot.",
    cue: "Routine first. Then shoot.",
    youtube: "free throw shooting form basketball",
    baseReps: "25 attempts", difficulty: 1, trackPR: "ftPct",
    why: "Free throws win games. Build the mental routine.",
    envs: ["halfct","hoop"] },

  { id: "sh6", category: "shooting", name: "3-Point Shooting (Spots)",
    description: "Shots from 3-point line, all 5 spots.",
    prescription: "5 spots around the 3-point arc: both corners, both wings, top. Shoot 10 threes from each spot. 50 total. Aim for 18+ makes. Don't move to the next spot until you're hitting at least 3 of 5.",
    cue: "Legs into your shot. Land balanced.",
    youtube: "3 point shooting drill basketball",
    baseReps: "50 threes, aim for 18+ makes", difficulty: 3,
    why: "Range-extending shot mechanics.",
    envs: ["halfct","hoop"] },

  { id: "sh7", category: "shooting", name: "Off-the-Dribble Pull-Up",
    description: "Dribble from top of key, 1-2 stop, pull-up jumper.",
    prescription: "Start at half court. Speed dribble to the elbow, plant on a 1-2 step, rise straight up for a pull-up jumper. Get rebound, walk back. 25 makes total. Alternate dribble hand each rep.",
    cue: "Square up before you go up. No drift.",
    youtube: "pull up jumper drill basketball",
    baseReps: "25 makes", difficulty: 3,
    why: "Most realistic shot in a real game off the dribble.",
    envs: ["halfct","hoop"] },

  { id: "sh8", category: "shooting", name: "Beat the Pro",
    description: "1 point per make, 2 for missed shot, race to 11.",
    prescription: "Start at any spot beyond the free throw line. You get 1 point per make, the 'pro' gets 2 points per miss. First to 11 wins. If 'pro' beats you, restart. Move spots after each make.",
    cue: "Pressure shot every time.",
    youtube: "beat the pro shooting drill basketball",
    baseReps: "Race to 11", difficulty: 2,
    why: "Pressure-cooker shooting practice.",
    envs: ["halfct","hoop"] },

  { id: "sh9", category: "shooting", name: "Around the World",
    description: "7 spots around the arc. Make at each before moving.",
    prescription: "7 spots: both corners, both short corners (15 ft), both wings, top of key. Make a shot from each spot before moving to the next. Miss = stay at that spot until you make it. Goal: complete the loop in under 25 shots.",
    cue: "Same form every spot.",
    youtube: "around the world basketball shooting drill",
    baseReps: "Complete loop", difficulty: 2,
    why: "Mid-range and 3-point shooting from game spots.",
    envs: ["halfct","hoop"] },

  { id: "sh10", category: "shooting", name: "Game Speed Threes",
    description: "Sprint to spot, catch, shoot.",
    prescription: "Start at the baseline. Sprint to the wing 3-point line. Catch a self-pass off the rim, square, shoot in rhythm. Sprint back to baseline, repeat. 20 shots total — track makes.",
    cue: "Sprint hard, then settle into your shot.",
    youtube: "game speed shooting drill basketball",
    baseReps: "20 shots", difficulty: 3,
    why: "Cardio + shooting under fatigue, game realistic.",
    envs: ["halfct","hoop"] },

  // ============================================================
  // FINISHING
  // ============================================================
  { id: "fin1", category: "finishing", name: "Reverse Layups",
    description: "Layups from opposite side of the rim.",
    prescription: "Start under the rim. Drive to the right side, finish reverse on the left side of the rim using your right hand. Then drive left, finish reverse on the right with your left hand. 20 makes total — alternate sides.",
    cue: "Use the rim as a shield.",
    youtube: "reverse layup drill basketball",
    baseReps: "20 makes", difficulty: 2,
    why: "Avoid blocks by using the rim as protection.",
    envs: ["halfct","hoop"] },

  { id: "fin2", category: "finishing", name: "Floater (Runner)",
    description: "Mid-range push shot from inside the paint.",
    prescription: "Start at the elbow. Take 1 dribble toward the rim and stop at the dotted-line area. Push the ball up softly with one hand — high arc, off the backboard. 25 makes from each elbow.",
    cue: "Soft push. High arc.",
    youtube: "floater drill basketball",
    baseReps: "50 makes total", difficulty: 3,
    why: "Counter for shot blockers and trees in the paint.",
    envs: ["halfct","hoop"] },

  { id: "fin3", category: "finishing", name: "Euro Step",
    description: "1-2 step finish around defender.",
    prescription: "Start at the free throw line. Drive to the rim — take a hard step right (gather), then a longer step left to dodge an imaginary defender, finish with the right hand. 15 makes each direction.",
    cue: "First step short, second step long.",
    youtube: "euro step finish drill basketball",
    baseReps: "30 makes total", difficulty: 3,
    why: "Avoid contact at the rim, game-changing finishing move.",
    envs: ["halfct","hoop"] },

  { id: "fin4", category: "finishing", name: "Layup Lines (Both Hands)",
    description: "Right and left hand layups.",
    prescription: "Start at the right elbow. Take 2 dribbles, finish a right-hand layup. Get rebound, walk to the left elbow, take 2 dribbles, finish a left-hand layup. 30 makes total, alternating hands.",
    cue: "Same hand as foot. Right hand, right foot up.",
    youtube: "basic layup drill basketball form",
    baseReps: "30 makes alternating", difficulty: 1,
    why: "Foundational finishing — must be automatic both hands.",
    envs: ["halfct","hoop"] },

  { id: "fin5", category: "finishing", name: "Power Layup",
    description: "Two-foot jump finish through contact.",
    prescription: "Start at the right block. Take one strong dribble, jump off two feet, finish strong off the glass with your right hand. Get rebound, switch to left block, two-foot jump, left-hand finish. 20 makes each side.",
    cue: "Jump off two feet. Brace for contact.",
    youtube: "power layup drill basketball",
    baseReps: "40 makes total", difficulty: 2,
    why: "Finish through contact, draw fouls.",
    envs: ["halfct","hoop"] },

  // ============================================================
  // FOOTWORK
  // ============================================================
  { id: "ft1", category: "footwork", name: "Jump Stops",
    description: "Sprint, jump stop, hold balance.",
    prescription: "Sprint from baseline to free throw line. Jump-stop (land on both feet at same time). Hold for 1 second balanced. Pivot 180° on either foot. Sprint back. 10 reps.",
    cue: "Land balanced. Knees bent.",
    youtube: "jump stop drill basketball footwork",
    baseReps: "10 reps", difficulty: 1,
    why: "Stop on a dime without traveling, set up triple threat.",
    envs: ["fullct","halfct","hoop","nohoop"] },

  { id: "ft2", category: "footwork", name: "Pivot Drills",
    description: "Front pivot, reverse pivot from triple threat.",
    prescription: "Stand in triple threat with a ball. Front pivot 90° on left foot — feel the rotation in your hips. Reset. Reverse pivot 90° on left foot. Reset. Switch pivot foot. Do 20 pivots each foot, each direction.",
    cue: "Stay low. Don't lift your pivot foot.",
    youtube: "pivot drill basketball footwork",
    baseReps: "80 pivots total", difficulty: 1,
    why: "Foundation of post moves and triple threat.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "ft3", category: "footwork", name: "Defensive Slides",
    description: "Lateral slides in stance, no crossing feet.",
    prescription: "Get in defensive stance — wide base, hands up. Slide laterally for 5 yards (or wing to wing), pause, slide back. Don't cross your feet. 10 round trips, no rest.",
    cue: "Stay low. Hands active. Don't bounce.",
    youtube: "defensive slide drill basketball",
    baseReps: "10 round trips", difficulty: 2,
    why: "On-ball defense fundamentals.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "ft4", category: "footwork", name: "Closeout Drill",
    description: "Sprint, breakdown into stance, contest.",
    prescription: "Start under the rim. Sprint to the 3-point line. Last 3 steps, chop your feet quickly into defensive stance with one hand high. Hold for 1 second. Backpedal to start. 10 reps.",
    cue: "Sprint, then chop. Don't fly past.",
    youtube: "closeout drill basketball defense",
    baseReps: "10 reps", difficulty: 2,
    why: "Most important defensive movement — closing out without overrunning.",
    envs: ["halfct","hoop"] },

  // ============================================================
  // DEFENSE
  // ============================================================
  { id: "df1", category: "defense", name: "Stance Holds",
    description: "Hold low defensive stance for time.",
    prescription: "Get in defensive stance: feet wider than shoulders, butt down, hands up and active. Hold for 30 seconds. Rest 15 seconds. 4 sets. Each set, push to drop your stance lower.",
    cue: "Butt down. Hands moving.",
    youtube: "defensive stance drill basketball",
    baseReps: "4 sets x 30 sec", difficulty: 1,
    why: "Builds the leg strength and habit to stay low on defense.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "df2", category: "defense", name: "Zigzag Slides",
    description: "Defensive slides in zigzag pattern.",
    prescription: "Start at one corner of the half court. Slide diagonally to the opposite elbow. Pivot, slide to the opposite corner. Repeat back. 4 full zigzags down and back.",
    cue: "Drop step on every change of direction.",
    youtube: "zigzag defensive slide drill basketball",
    baseReps: "4 trips down and back", difficulty: 2,
    why: "Real defensive movement, change of direction under fatigue.",
    envs: ["halfct","fullct"] },

  { id: "df3", category: "defense", name: "Mirror Drill",
    description: "Mirror partner's movements (or shadow yourself).",
    prescription: "If you have a partner: face each other, they move randomly, you mirror in defensive stance. 30 seconds, switch. If solo: pick imaginary spots and react quickly to each one. 4 rounds of 30 seconds.",
    cue: "React, don't anticipate.",
    youtube: "mirror drill basketball defense",
    baseReps: "4 sets x 30 sec", difficulty: 2,
    why: "Reactive defense — the most realistic kind.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "df4", category: "defense", name: "Charge Drill (Solo)",
    description: "Practice taking charges — set position, fall back.",
    prescription: "Set position: feet planted, arms crossed over chest. Fall straight back onto your butt — let yourself fall, don't catch yourself. Get up immediately, set, fall again. 10 reps. (No partner needed — practice the falling technique.)",
    cue: "Hands across chest. Fall back, not forward.",
    youtube: "taking a charge drill basketball",
    baseReps: "10 reps", difficulty: 2,
    why: "Learn to take charges safely — game-changing defensive play.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  // ============================================================
  // CONDITIONING
  // ============================================================
  { id: "cd1", category: "conditioning", name: "Suicides",
    description: "Touch each line: free throw, half, far free throw, far baseline.",
    prescription: "Start at the baseline. Sprint to the free throw line, touch it, sprint back to baseline. Sprint to half court, touch, back. Sprint to far free throw, touch, back. Sprint to far baseline, touch, back. That's 1 round. Do 4 rounds. Time yourself.",
    cue: "Touch each line low. Push off hard.",
    youtube: "suicide running drill basketball",
    baseReps: "4 rounds, time it", difficulty: 3, trackPR: "suicideTime",
    why: "Game-shape conditioning. Every basketball player runs these.",
    envs: ["fullct"] },

  { id: "cd2", category: "conditioning", name: "Sideline to Sideline",
    description: "Sprint between sidelines.",
    prescription: "Start on one sideline. Sprint across to the opposite sideline. Touch the line. Sprint back. 10 round trips, rest 30 seconds, 10 more.",
    cue: "Push off, don't jog.",
    youtube: "sideline to sideline sprint basketball",
    baseReps: "20 round trips", difficulty: 2,
    why: "Lateral conditioning — game movement is rarely straight ahead.",
    envs: ["fullct","halfct"] },

  { id: "cd3", category: "conditioning", name: "Mile Run",
    description: "1 mile timed run, push pace.",
    prescription: "Run 1 mile as fast as you can sustain. If on a track, that's 4 laps. Track your time. Aim to beat it next time.",
    cue: "Steady, controlled breathing.",
    youtube: "1 mile run pacing tips",
    baseReps: "1 mile timed", difficulty: 2, trackPR: "mileTime",
    why: "Aerobic base for fourth-quarter legs.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "cd4", category: "conditioning", name: "Jump Rope Intervals",
    description: "Jump rope hard for time.",
    prescription: "Jump rope at high pace for 60 seconds. Rest 30 seconds. 8 rounds. Mix in singles, doubles, alternating feet — whatever keeps you moving.",
    cue: "Stay light on your toes.",
    youtube: "jump rope intervals basketball conditioning",
    baseReps: "8 rounds 60-30", difficulty: 2,
    why: "Footwork, calves, conditioning all in one.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "cd5", category: "conditioning", name: "Hill Sprints",
    description: "Find a hill, sprint up, walk down.",
    prescription: "Find a hill 30-50 yards long with a moderate slope. Sprint up at full effort, walk back down to recover. 10 sprints. If no hill: 100m sprints on flat with full walk-back recovery.",
    cue: "Drive your knees. Pump your arms.",
    youtube: "hill sprints workout",
    baseReps: "10 sprints", difficulty: 3,
    why: "Build explosive leg power and lung capacity.",
    envs: ["nohoop"] },

  { id: "cd6", category: "conditioning", name: "Tabata (Body Weight)",
    description: "20 sec on, 10 sec off — 8 rounds.",
    prescription: "Pick one movement: burpees, mountain climbers, or jump squats. Go all-out for 20 seconds, rest 10 seconds. 8 rounds total = 4 minutes. Should feel almost impossible by round 6.",
    cue: "Last 5 seconds: push harder.",
    youtube: "tabata workout basketball",
    baseReps: "8 rounds 20-10", difficulty: 3,
    why: "Massive aerobic + anaerobic stimulus in 4 minutes.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  // ============================================================
  // WARMUP
  // ============================================================
  { id: "wu1", category: "warmup", name: "Dynamic Stretch",
    description: "Leg swings, arm circles, hip openers.",
    prescription: "10 leg swings forward/back each leg. 10 leg swings side-to-side each leg. 10 arm circles forward, 10 backward. 10 hip openers each side. 10 walking lunges with twist. Total: 5 minutes.",
    cue: "Movement, not stretches you hold.",
    youtube: "dynamic warmup basketball",
    baseReps: "Full sequence, 5 min", difficulty: 1,
    why: "Prep muscles for explosive movement, prevent injury.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "wu2", category: "warmup", name: "Light Jog + Skips",
    description: "Easy jog, high knees, butt kicks.",
    prescription: "2 minutes easy jog. Then 30 seconds high knees. 30 seconds butt kicks. 30 seconds skips. 30 seconds carioca (cross-step laterally). Repeat the 4 movements once more. Total: 4 minutes.",
    cue: "Smooth and controlled, not max effort.",
    youtube: "basketball pregame warmup",
    baseReps: "4 min total", difficulty: 1,
    why: "Heart rate up, joints lubricated.",
    envs: ["fullct","halfct","hoop","nohoop"] },

  { id: "wu3", category: "warmup", name: "Activation",
    description: "Glute bridges, bird dogs, plank.",
    prescription: "20 glute bridges. 10 bird dogs each side. 30-second plank. 15 reverse lunges each leg. Repeat sequence twice. Total: 4 minutes.",
    cue: "Wake up your glutes and core.",
    youtube: "movement prep activation drills basketball",
    baseReps: "Full sequence x 2", difficulty: 1,
    why: "Activates glutes and core before training.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },
];

const STRENGTH_DRILLS = [
  // ============================================================
  // UPPER BODY
  // ============================================================
  { id: "u1", category: "upper", name: "Push-Ups",
    description: "Chest to ground, full lockout. Strict form.",
    prescription: "Get in plank with hands shoulder-width apart. Lower your chest to the ground (not your hips), push back up to full lockout. 3 sets to failure. Rest 90 seconds between sets. Track your max set.",
    cue: "Chest to floor. Body in a line.",
    youtube: "push up form proper technique",
    baseReps: "3 sets x max reps", difficulty: 1,
    why: "Chest, shoulders, triceps — pushing strength.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"], trackPR: "maxPushups" },

  { id: "u2", category: "upper", name: "Pull-Ups",
    description: "Full hang to chin over bar. Dead hang assisted if needed.",
    prescription: "Hang from a bar, palms facing away, hands shoulder-width. Pull yourself up until your chin clears the bar. Lower with control to dead hang. 3 sets to failure. Rest 2 minutes between sets. If you can't do reps yet: do negatives (jump up, lower for 5 seconds, repeat).",
    cue: "Chin over bar. Don't kip.",
    youtube: "pull up form proper technique",
    baseReps: "3 sets x max reps", difficulty: 3,
    why: "Back and biceps — critical for rebounding.",
    envs: ["homegym","gym"], trackPR: "maxPullups" },

  { id: "u3", category: "upper", name: "Pike Push-Ups",
    description: "Hips high, push head toward ground. Shoulder focus.",
    prescription: "Get in downward-dog position: hands and feet on the ground, butt high in the air, body in an inverted V. Bend elbows, lower your head toward the ground between your hands. Push back up. 3 sets of 8-12.",
    cue: "Hips high. Head between hands.",
    youtube: "pike push up form",
    baseReps: "3 sets x 8-12", difficulty: 2,
    why: "Builds overhead pressing strength.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "u4", category: "upper", name: "Diamond Push-Ups",
    description: "Hands close together forming a diamond shape.",
    prescription: "Push-up position with hands together under your chest, thumbs and index fingers touching to make a diamond. Lower your chest to the diamond, push back up. 3 sets of 8-12. Harder than regular push-ups.",
    cue: "Elbows back, not flared.",
    youtube: "diamond push up form basketball",
    baseReps: "3 sets x 8-12", difficulty: 2,
    why: "Heavy triceps work, important for shooting strength.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "u5", category: "upper", name: "Bench Press",
    description: "Barbell or dumbbell bench press.",
    prescription: "Lie flat on a bench. Use a weight you can do for 8-12 reps with good form. Lower the bar/dumbbells to your chest under control, press up. 4 sets of 8-12. Add weight when you hit 12 reps cleanly.",
    cue: "Squeeze chest, don't bounce off chest.",
    youtube: "bench press form proper technique",
    baseReps: "4 sets x 8-12", difficulty: 2,
    why: "Builds upper body pushing strength.",
    envs: ["homegym","gym"] },

  { id: "u6", category: "upper", name: "Dumbbell Rows",
    description: "Single arm rows with dumbbell.",
    prescription: "Hand and knee on a bench, opposite leg planted. Hold a dumbbell in your free hand, arm extended. Row the dumbbell to your hip, squeeze your back. Lower with control. 4 sets of 10 reps each arm.",
    cue: "Pull with your back, not your arm.",
    youtube: "dumbbell row form proper technique",
    baseReps: "4 sets x 10 each arm", difficulty: 2,
    why: "Pulling strength to balance pushing — prevent shoulder injuries.",
    envs: ["homegym","gym"] },

  { id: "u7", category: "upper", name: "Shoulder Press",
    description: "Overhead press with dumbbells or barbell.",
    prescription: "Stand with dumbbells at shoulder height. Press them straight overhead until arms are locked out. Lower with control to shoulder height. 3 sets of 8-10.",
    cue: "Don't lean back. Core tight.",
    youtube: "overhead press form dumbbell",
    baseReps: "3 sets x 8-10", difficulty: 2,
    why: "Shoulder strength for shooting and rebounds.",
    envs: ["homegym","gym"] },

  { id: "u8", category: "upper", name: "Dips",
    description: "Parallel bar dips, full range.",
    prescription: "On parallel bars or a sturdy chair edge: support yourself on locked arms. Lower until upper arms are parallel to the ground. Push back up to lockout. 3 sets of 8-12.",
    cue: "Lean slightly forward. Full range.",
    youtube: "dips chest triceps form",
    baseReps: "3 sets x 8-12", difficulty: 3,
    why: "Heavy triceps and chest, advanced bodyweight strength.",
    envs: ["homegym","gym"] },

  { id: "u9", category: "upper", name: "Pike Hold",
    description: "Pike position handstand prep, hold time.",
    prescription: "Pike push-up position (downward dog). Hold the position with no movement, building up handstand strength. 30-60 seconds, 3 sets.",
    cue: "Stack your shoulders over your hands.",
    youtube: "pike hold handstand progression",
    baseReps: "3 sets x 30-60 sec", difficulty: 2,
    why: "Builds pressing strength and prep for handstand work.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  // ============================================================
  // LOWER BODY
  // ============================================================
  { id: "l1", category: "lower", name: "Bodyweight Squats",
    description: "Full depth, knees track over toes.",
    prescription: "Feet shoulder-width, toes slightly out. Sit your hips back like sitting in a chair, lower until thighs are parallel to ground. Drive up through your heels. 4 sets of 20 reps.",
    cue: "Knees out, chest up.",
    youtube: "bodyweight squat form proper technique",
    baseReps: "4 sets x 20", difficulty: 1,
    why: "Foundation for jumping and explosive movement.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "l2", category: "lower", name: "Lunges",
    description: "Walking or static lunges.",
    prescription: "Take a long step forward, drop straight down until back knee almost touches ground. Drive back up to standing. Alternate legs. 3 sets of 10 reps each leg.",
    cue: "Keep your front knee over your ankle.",
    youtube: "lunge form proper technique",
    baseReps: "3 sets x 10 each leg", difficulty: 1,
    why: "Single-leg strength — basketball is mostly single-leg movement.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "l3", category: "lower", name: "Bulgarian Split Squats",
    description: "Rear foot elevated split squat.",
    prescription: "Stand 2 feet in front of a bench. Place the top of one foot on the bench behind you. Drop straight down on your front leg, until the back knee almost touches ground. Drive up through the front heel. 3 sets of 10 each leg.",
    cue: "Drop straight down, not forward.",
    youtube: "bulgarian split squat form",
    baseReps: "3 sets x 10 each leg", difficulty: 2,
    why: "Brutal single-leg strength, mimics jumping mechanics.",
    envs: ["homegym","gym"] },

  { id: "l4", category: "lower", name: "Goblet Squats",
    description: "Hold dumbbell at chest, squat deep.",
    prescription: "Hold a dumbbell vertically at your chest. Feet shoulder-width. Squat down deep — elbows should brush the inside of your knees at the bottom. Drive up. 3 sets of 12.",
    cue: "Elbows inside knees at the bottom.",
    youtube: "goblet squat form basketball",
    baseReps: "3 sets x 12", difficulty: 2,
    why: "Loaded squat pattern, easier on the spine than barbell.",
    envs: ["homegym","gym"] },

  { id: "l5", category: "lower", name: "Romanian Deadlifts",
    description: "Hip hinge with dumbbells or barbell.",
    prescription: "Hold dumbbells at thighs. Slight bend in knees. Push your hips back, lower the weight to mid-shin keeping back flat. Squeeze glutes to come up. 3 sets of 10.",
    cue: "Push hips back. Back stays flat.",
    youtube: "romanian deadlift form proper technique",
    baseReps: "3 sets x 10", difficulty: 2,
    why: "Hamstrings and glutes — sprint speed and jumping power.",
    envs: ["homegym","gym"] },

  { id: "l6", category: "lower", name: "Step-Ups",
    description: "Step onto a box, drive knee up.",
    prescription: "Find a sturdy box or bench at knee height. Step up with your right foot, drive your left knee up high at the top. Step down with control. 3 sets of 10 each leg.",
    cue: "Drive through the box foot, not the floor.",
    youtube: "step up exercise form basketball",
    baseReps: "3 sets x 10 each leg", difficulty: 1,
    why: "Single-leg explosiveness, jumping power.",
    envs: ["homegym","gym","fullct","halfct"] },

  { id: "l7", category: "lower", name: "Wall Sit",
    description: "Back against wall, thighs parallel, hold.",
    prescription: "Stand with your back against a wall. Slide down until your thighs are parallel to the ground (90° at hips and knees). Hold. 3 sets, building from 30 seconds to 60 seconds.",
    cue: "Press your low back into the wall.",
    youtube: "wall sit exercise",
    baseReps: "3 sets x 30-60 sec", difficulty: 2,
    why: "Quad endurance for fourth-quarter legs.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "l8", category: "lower", name: "Calf Raises",
    description: "Heels up to max height, hold briefly.",
    prescription: "Stand on the edge of a step, balls of feet on, heels hanging off. Push up onto your toes as high as possible, hold for 1 second, lower below the step. 4 sets of 20.",
    cue: "Full range. Pause at the top.",
    youtube: "calf raises form proper technique",
    baseReps: "4 sets x 20", difficulty: 1,
    why: "Calves drive every jump and first step.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "l9", category: "lower", name: "Single Leg Glute Bridge",
    description: "One foot on ground, drive hips up.",
    prescription: "Lie on your back, one foot flat on ground knee bent, other leg extended. Drive your hips up using your glute. Pause at top, lower with control. 3 sets of 10 each leg.",
    cue: "Squeeze glute hard at the top.",
    youtube: "single leg glute bridge form",
    baseReps: "3 sets x 10 each leg", difficulty: 1,
    why: "Glute strength prevents hamstring pulls and improves jump.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "l10", category: "lower", name: "Pistol Squat Progression",
    description: "Single leg squat, hold for balance.",
    prescription: "Stand on one leg. Lower yourself as deep as you can on that leg while extending the other forward. Use a wall for support if needed. 3 sets of 5 each leg.",
    cue: "Keep your chest up. Don't fall back.",
    youtube: "pistol squat progression form",
    baseReps: "3 sets x 5 each leg", difficulty: 3,
    why: "Most demanding single-leg strength move.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "l11", category: "lower", name: "Back Squats",
    description: "Barbell back squat, full depth.",
    prescription: "Bar on your traps. Feet shoulder-width. Squat to parallel or below. Drive up through midfoot. 4 sets of 6-8 reps. Use a weight you can do with perfect form.",
    cue: "Keep your chest up. Push the floor away.",
    youtube: "back squat form proper technique",
    baseReps: "4 sets x 6-8", difficulty: 3,
    why: "Heaviest leg strength move — directly translates to jumping.",
    envs: ["gym"] },

  { id: "l12", category: "lower", name: "Front Squats",
    description: "Barbell on shoulders, front rack.",
    prescription: "Barbell rests on your front shoulders, elbows pointing forward. Squat down keeping your chest tall. 3 sets of 6-8.",
    cue: "Elbows up. Chest up.",
    youtube: "front squat form proper technique",
    baseReps: "3 sets x 6-8", difficulty: 3,
    why: "Quad-dominant squat, more upright like real basketball stance.",
    envs: ["gym"] },

  { id: "l13", category: "lower", name: "Trap Bar Deadlift",
    description: "Hex bar deadlift from floor.",
    prescription: "Step inside trap bar, grip handles. Sit hips down with chest up. Drive through your heels to stand up tall. Lower with control. 4 sets of 5.",
    cue: "Chest proud. Push the floor down.",
    youtube: "trap bar deadlift form basketball",
    baseReps: "4 sets x 5", difficulty: 3,
    why: "Total body power, basketball-friendly deadlift variation.",
    envs: ["gym"] },

  { id: "l14", category: "lower", name: "Box Step-Ups (Loaded)",
    description: "Step-ups holding dumbbells.",
    prescription: "Hold dumbbells at your sides. Step up onto a box with your right foot, drive up explosively, drive left knee up at the top. Step down. 3 sets of 8 each leg.",
    cue: "Explode up. Don't push off the back foot.",
    youtube: "loaded step up basketball plyometric",
    baseReps: "3 sets x 8 each leg", difficulty: 2,
    why: "Single-leg power, mimics jumping off one foot.",
    envs: ["homegym","gym"] },

  // ============================================================
  // CORE
  // ============================================================
  { id: "c1", category: "core", name: "Plank",
    description: "Forearm plank, body straight.",
    prescription: "Forearms on the ground, body in a straight line from head to heels. Hold without sagging. 3 sets of 60 seconds. Track your max hold time.",
    cue: "Squeeze glutes. Don't sag.",
    youtube: "plank form proper technique",
    baseReps: "3 sets x 60 sec", difficulty: 1, trackPR: "plankHold",
    why: "Core stability — base for all athletic movement.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "c2", category: "core", name: "Side Planks",
    description: "Side plank both sides.",
    prescription: "Lie on your side, prop yourself up on one forearm. Stack your feet, lift your hips. Body should be in a straight line. Hold 30 seconds each side. 3 rounds.",
    cue: "Hips up. Don't sag.",
    youtube: "side plank form proper technique",
    baseReps: "3 sets x 30 sec each side", difficulty: 2,
    why: "Lateral core for change of direction.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "c3", category: "core", name: "Russian Twists",
    description: "Seated, feet up, twist side to side.",
    prescription: "Sit on floor, lean back 45°, lift your feet off the ground. Hold a weight or just clasp hands. Twist side to side touching the ground next to your hip. 3 sets of 30 total reps.",
    cue: "Slow and controlled. Don't whip.",
    youtube: "russian twist core exercise",
    baseReps: "3 sets x 30 reps", difficulty: 2,
    why: "Rotational core for shooting, passing, defensive movement.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "c4", category: "core", name: "Hanging Leg Raises",
    description: "Hang from bar, raise legs to 90°.",
    prescription: "Hang from a pull-up bar, dead hang. Without swinging, raise your legs straight up to 90° (or as high as you can). Lower with control. 3 sets of 10.",
    cue: "Don't swing. Use your core.",
    youtube: "hanging leg raise form proper technique",
    baseReps: "3 sets x 10", difficulty: 3,
    why: "Lower abs and hip flexors — explosive jumping prep.",
    envs: ["homegym","gym"] },

  { id: "c5", category: "core", name: "Dead Bug",
    description: "On back, opposite arm/leg extension.",
    prescription: "Lie on back, arms straight up, knees at 90°. Extend opposite arm and leg slowly without arching back. Return, switch. 3 sets of 10 each side.",
    cue: "Press low back to floor. Slow.",
    youtube: "dead bug exercise core",
    baseReps: "3 sets x 10 each side", difficulty: 1,
    why: "Anti-extension core — protects back during athletic moves.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "c6", category: "core", name: "V-Ups",
    description: "Hands and feet meet at the top.",
    prescription: "Lie flat on your back. In one motion, raise your legs and torso to meet at the top — body forms a V shape. Lower with control. 3 sets of 15.",
    cue: "Slow up, slow down.",
    youtube: "v up exercise core",
    baseReps: "3 sets x 15", difficulty: 2,
    why: "Full core strength, including lower abs.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "c7", category: "core", name: "Bird Dog",
    description: "Quadruped opposite arm/leg.",
    prescription: "On hands and knees. Extend right arm forward and left leg back at the same time, until both are parallel to ground. Hold 2 seconds. Switch. 3 sets of 10 each side.",
    cue: "Squeeze glute. Don't twist.",
    youtube: "bird dog core exercise",
    baseReps: "3 sets x 10 each side", difficulty: 1,
    why: "Cross-body core stability, helps prevent low back pain.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "c8", category: "core", name: "Hollow Body Hold",
    description: "Lie on back, lower back pressed flat, hold.",
    prescription: "Lie on back. Press your low back into the ground. Lift your legs and shoulders off the ground 6 inches. Arms overhead. Hold. 3 sets, 30-45 seconds.",
    cue: "Low back glued to the floor.",
    youtube: "hollow body hold gymnastics",
    baseReps: "3 sets x 30-45 sec", difficulty: 3,
    why: "Gymnastics-quality core — total tension control.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  // ============================================================
  // PLYOMETRICS
  // ============================================================
  { id: "p1", category: "plyo", name: "Box Jumps",
    description: "Jump onto box, step down.",
    prescription: "Find a sturdy box 18-24\" tall. Stand 1 foot away. Bend, swing arms back, then explode up onto the box landing softly. Step down (don't jump down). 4 sets of 5.",
    cue: "Land soft. Stand tall on the box.",
    youtube: "box jump form proper technique",
    baseReps: "4 sets x 5", difficulty: 2,
    why: "Vertical jump development, explosive power.",
    envs: ["homegym","gym"] },

  { id: "p2", category: "plyo", name: "Broad Jumps",
    description: "Forward jump for distance.",
    prescription: "Stand at a line. Bend, swing arms back, then explode forward jumping as far as possible with both feet. Land soft and balanced. Walk back to start. 5 sets of 3 jumps.",
    cue: "Big arm swing. Land balanced.",
    youtube: "broad jump basketball plyometric",
    baseReps: "5 sets x 3", difficulty: 2,
    why: "Horizontal explosive power for first step.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "p3", category: "plyo", name: "Squat Jumps",
    description: "Squat, explode up, land softly.",
    prescription: "Squat down to thighs parallel. Explode straight up jumping as high as possible. Land soft, immediately drop into next squat. 4 sets of 8.",
    cue: "Land soft. Don't pause at the top.",
    youtube: "squat jump form basketball",
    baseReps: "4 sets x 8", difficulty: 2,
    why: "Vertical jump training without equipment.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "p4", category: "plyo", name: "Tuck Jumps",
    description: "Jump up, knees to chest.",
    prescription: "Stand tall. Jump straight up bringing your knees to your chest at the peak. Land soft, immediately repeat. 3 sets of 10.",
    cue: "Knees to chest, not chest to knees.",
    youtube: "tuck jump exercise basketball",
    baseReps: "3 sets x 10", difficulty: 3,
    why: "Hip flexor explosiveness for jumping with knees up.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "p5", category: "plyo", name: "Lateral Bounds",
    description: "Side-to-side jumps for distance.",
    prescription: "Stand on one foot. Push off explosively to the side, landing on your other foot. Stick the landing. Push off again the other direction. 3 sets of 10 reps total.",
    cue: "Stick the landing each time.",
    youtube: "lateral bounds plyometric basketball",
    baseReps: "3 sets x 10", difficulty: 2,
    why: "Lateral explosive power, defensive slide power.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  // ============================================================
  // MOBILITY
  // ============================================================
  { id: "m1", category: "mobility", name: "World's Greatest Stretch",
    description: "Lunge with rotation, hamstring stretch.",
    prescription: "Step into deep lunge. Place opposite hand on floor inside front foot. Reach the same-side hand up to the ceiling, opening your chest. Hold 2 seconds. Switch sides. 5 reps each side.",
    cue: "Open your chest. Look up.",
    youtube: "worlds greatest stretch mobility",
    baseReps: "5 each side", difficulty: 1,
    why: "Hits hips, hamstrings, t-spine — covers most basketball mobility issues.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "m2", category: "mobility", name: "Hip 90/90",
    description: "Sit with both hips at 90°, switch sides.",
    prescription: "Sit with one leg in front bent at 90°, the other behind also at 90°. Sit tall. Hold 30 seconds. Lift both knees and rotate to switch sides. 3 rounds.",
    cue: "Sit up tall. Hips, not back.",
    youtube: "hip 90 90 mobility drill",
    baseReps: "3 rounds 30 sec each", difficulty: 2,
    why: "Hip rotation mobility — defensive stance and crossovers.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "m3", category: "mobility", name: "Cat-Cow",
    description: "Spine articulation through full range.",
    prescription: "On hands and knees. Arch your back lifting head and tail (cow). Then round your back tucking head and tail (cat). Move slowly with breath. 15 reps.",
    cue: "Slow. Breathe with each motion.",
    youtube: "cat cow stretch spine mobility",
    baseReps: "15 reps", difficulty: 1,
    why: "Spine mobility, low back relief.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "m4", category: "mobility", name: "Couch Stretch",
    description: "Hip flexor stretch with back foot elevated.",
    prescription: "Place one foot on a couch or low surface, knee on ground, other foot in lunge in front. Squeeze glute of back leg, push hips forward. Hold 60 seconds each leg.",
    cue: "Squeeze glute. Tall posture.",
    youtube: "couch stretch hip flexor",
    baseReps: "60 sec each leg", difficulty: 2,
    why: "Opens up hip flexors — tight hips kill jumping power.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },

  { id: "m5", category: "mobility", name: "Foam Roll Lower Body",
    description: "Quads, IT band, calves, glutes.",
    prescription: "60 seconds each: quads, IT band (outer thigh), glutes, calves. If you find a tender spot, hold there for 20-30 seconds. Total: 4-5 minutes.",
    cue: "Pause on tender spots. Breathe.",
    youtube: "foam rolling lower body basketball",
    baseReps: "4-5 min total", difficulty: 1,
    why: "Recovery and tissue quality — keeps you injury free.",
    envs: ["fullct","halfct","hoop","nohoop","homegym","gym"] },
];

// WEEKLY TEMPLATE - workout generator filters drills by env
const WEEKLY_TEMPLATE = {
  monday: {
    name: "Monday", type: "training", title: "Lower + Skill", duration: 60,
    blocks: [
      { label: "Warmup", category: "warmup", count: 1 },
      { label: "Skill: Ball Handling", category: "ball-handling", count: 2 },
      { label: "Skill: Shooting", category: "shooting", count: 2 },
      { label: "Strength: Lower", category: "lower", count: 3 },
      { label: "Core", category: "core", count: 2 },
    ]
  },
  tuesday: {
    name: "Tuesday", type: "training", title: "Game Skills + Upper", duration: 60,
    blocks: [
      { label: "Warmup", category: "warmup", count: 1 },
      { label: "Footwork", category: "footwork", count: 2 },
      { label: "Finishing", category: "finishing", count: 2 },
      { label: "Strength: Upper", category: "upper", count: 3 },
      { label: "Core", category: "core", count: 1 },
    ]
  },
  wednesday: {
    name: "Wednesday", type: "recovery", title: "Active Recovery", duration: 30,
    blocks: [
      { label: "Mobility", category: "mobility", count: 3 },
      { label: "Light Shooting", category: "shooting", count: 2, filter: "sh1,sh5" },
      { label: "Core", category: "core", count: 2 },
    ]
  },
  thursday: {
    name: "Thursday", type: "training", title: "Full Body + Skills", duration: 60,
    blocks: [
      { label: "Warmup", category: "warmup", count: 1 },
      { label: "Ball Handling", category: "ball-handling", count: 2 },
      { label: "Footwork", category: "footwork", count: 1 },
      { label: "Shooting", category: "shooting", count: 2 },
      { label: "Defense", category: "defense", count: 1 },
      { label: "Strength: Upper", category: "upper", count: 2 },
      { label: "Strength: Lower", category: "lower", count: 1 },
    ]
  },
  friday: {
    name: "Friday", type: "training", title: "Pre-Game Sharpener", duration: 45,
    blocks: [
      { label: "Warmup", category: "warmup", count: 1 },
      { label: "Shooting", category: "shooting", count: 3 },
      { label: "Finishing", category: "finishing", count: 2 },
      { label: "Free Throws", category: "shooting", count: 1, filter: "sh5" },
      { label: "Mobility", category: "mobility", count: 1 },
    ]
  },
  saturday: {
    name: "Saturday", type: "gameday", title: "Game Day Warmup", duration: 30,
    blocks: [
      { label: "Dynamic Warmup", category: "warmup", count: 2 },
      { label: "Form Shooting", category: "shooting", count: 1, filter: "sh1" },
      { label: "Spot Shooting", category: "shooting", count: 1, filter: "sh3" },
    ]
  },
  sunday: {
    name: "Sunday", type: "gameday", title: "Game Day or Rest", duration: 25,
    blocks: [
      { label: "Light Mobility", category: "mobility", count: 2 },
      { label: "Light Shooting", category: "shooting", count: 1, filter: "sh1" },
    ]
  }
};

const PREGAME_WARMUP = [
  "Foam roll legs (5 min)",
  "Dynamic stretch series (5 min)",
  "Light jog + skips (3 min)",
  "Form shooting close range (5 min)",
  "Spot shooting all 5 spots (5 min)",
  "Free throws — 10 makes",
  "Visualize your role: defense, decisions, shots you'll take"
];

const POSTGAME_RECOVERY = [
  "Hydrate within 30 min",
  "Protein within 1 hour (chicken, eggs, shake)",
  "Foam roll legs",
  "Light stretch — focus on hips and quads",
  "Sleep 8+ hours tonight"
];

const BADGES = [
  { id: "streak3", name: "Lock In", icon: "🔒", desc: "3-day workout streak", criteria: { streak: 3 } },
  { id: "streak7", name: "Week One", icon: "⚡", desc: "7-day workout streak", criteria: { streak: 7 } },
  { id: "streak14", name: "Two Weeks Strong", icon: "💪", desc: "14-day streak", criteria: { streak: 14 } },
  { id: "streak30", name: "Month In", icon: "🔥", desc: "30-day streak", criteria: { streak: 30 } },
  { id: "streak60", name: "Two Months Deep", icon: "💎", desc: "60-day streak", criteria: { streak: 60 } },
  { id: "streak100", name: "100 Days Locked", icon: "👑", desc: "100-day streak", criteria: { streak: 100 } },
  { id: "work10", name: "Getting Started", icon: "🌱", desc: "10 workouts completed", criteria: { workouts: 10 } },
  { id: "work25", name: "Finding Rhythm", icon: "🎯", desc: "25 workouts completed", criteria: { workouts: 25 } },
  { id: "work50", name: "Fifty Deep", icon: "🥇", desc: "50 workouts completed", criteria: { workouts: 50 } },
  { id: "work100", name: "Century Club", icon: "💯", desc: "100 workouts completed", criteria: { workouts: 100 } },
  { id: "ft100", name: "Free Throw Apprentice", icon: "🎯", desc: "100 free throws made", criteria: { ftMade: 100 } },
  { id: "ft500", name: "Free Throw Pro", icon: "🏹", desc: "500 free throws made", criteria: { ftMade: 500 } },
  { id: "ft1000", name: "Free Throw Master", icon: "🌟", desc: "1000 free throws made", criteria: { ftMade: 1000 } },
  { id: "ft80pct", name: "Sharp Shooter", icon: "🎯", desc: "Hit 80%+ on a free throw set", criteria: { bestFtPct: 80 } },
  { id: "push100", name: "Push Up Hundred", icon: "💪", desc: "100 push-ups in one workout", criteria: { pushupsTotal: 100 } },
  { id: "push500", name: "Iron Chest", icon: "🦾", desc: "500 push-ups total", criteria: { pushupsTotal: 500 } },
  { id: "pull5", name: "Pull-Up Rookie", icon: "🆙", desc: "5+ pull-ups", criteria: { pullupPR: 5 } },
  { id: "pull10", name: "Pull-Up Beast", icon: "🦍", desc: "10+ pull-ups", criteria: { pullupPR: 10 } },
  { id: "game1", name: "Played the Game", icon: "🏀", desc: "First game logged", criteria: { games: 1 } },
  { id: "game10", name: "Season In", icon: "🎮", desc: "10 games logged", criteria: { games: 10 } },
  { id: "sleep7", name: "Well Rested", icon: "😴", desc: "7 nights of 8+ hours sleep", criteria: { sleepStreak: 7 } },
  { id: "checkin10", name: "Self Aware", icon: "✅", desc: "10 morning check-ins", criteria: { checkins: 10 } },
  { id: "checkin30", name: "Locked In Mind", icon: "🧠", desc: "30 morning check-ins", criteria: { checkins: 30 } },
];

// Expose globally so main app can read
if (typeof window !== 'undefined') {
  window.HOOPERS_DATA = {
    ENVIRONMENTS, BASKETBALL_DRILLS, STRENGTH_DRILLS, WEEKLY_TEMPLATE,
    PREGAME_WARMUP, POSTGAME_RECOVERY, BADGES
  };
}
